export interface BookProps { 
    books: { 
        coverImage?: string; 
        title: string; 
        author: string; 
        publisher: string; 
        publishYear?: string; 
        genre?: string; 
        id: string; 
        summary?: string; 
        tableOfContents?: string; 
        location?: number;
        bookSize: number;
        currentstate?: boolean; 
    } []; 
} 

export const BookLists: BookProps = {
    books: [
      {
        id: "1",
        title: "Clean Code",
        author: "Robert C. Martin",
        publisher: "Prentice Hall",
        publishYear: "2008-08-01",
        genre: "Programming",
        summary: "A Handbook of Agile Software Craftsmanship",
        tableOfContents: "Must Read for Developers",
        currentstate: true,
        location: 5, 
        bookSize: 1, 
        coverImage: "https://example.com/clean-code.jpg",
      },
      {
        id: "2",
        title: "The Pragmatic Programmer",
        author: "Andrew Hunt, David Thomas",
        publisher: "Addison-Wesley",
        publishYear: "1999-10-30",
        genre: "Programming",
        summary: "Your Journey to Mastery",
        tableOfContents: "Top Coding Books",
        currentstate: false,
        bookSize: 3, 
        coverImage: "https://example.com/pragmatic-programmer.jpg",
      },
      {
        id: "3",
        title: "Refactoring",
        author: "Martin Fowler",
        publisher: "Addison-Wesley",
        publishYear: "2018-11-20",
        genre: "Software Engineering",
        summary: "Improving the Design of Existing Code",
        tableOfContents: "Software Design",
        currentstate: true,
        location: 3, 
        bookSize: 2, 
        coverImage: "https://example.com/refactoring.jpg",
      },
      {
        id: "4",
        title: "Design Patterns",
        author: "Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides",
        publisher: "Addison-Wesley",
        publishYear: "1994-10-21",
        genre: "Software Design",
        summary: "Elements of Reusable Object-Oriented Software",
        tableOfContents: "Classic Books",
        currentstate: false,
        bookSize: 3, 
      },
      {
        id: "5",
        title: "You Don't Know JS",
        author: "Kyle Simpson",
        publisher: "O'Reilly Media",
        publishYear: "2015-12-28",
        genre: "JavaScript",
        summary: "Deep dive into JavaScript",
        tableOfContents: "JavaScript Essentials",
        currentstate: true,
        location: 3, 
        bookSize: 2, 
      },
      {
        id: "6",
        title: "JavaScript: The Good Parts",
        author: "Douglas Crockford",
        publisher: "O'Reilly Media",
        publishYear: "2008-05-15",
        genre: "JavaScript",
        summary: "Unearthing the Excellence in JavaScript",
        tableOfContents: "JavaScript Must Read",
        currentstate: false,
        bookSize: 1, 
      },
      {
        id: "7",
        title: "Eloquent JavaScript",
        author: "Marijn Haverbeke",
        publisher: "No Starch Press",
        publishYear: "2018-12-04",
        genre: "JavaScript",
        summary: "A Modern Introduction to Programming",
        tableOfContents: "Beginner Friendly",
        currentstate: true,
        location: 6, 
        bookSize: 1, 
      },
      {
        id: "8",
        title: "The Mythical Man-Month",
        author: "Frederick P. Brooks Jr.",
        publisher: "Addison-Wesley",
        publishYear: "1975-01-01",
        genre: "Software Engineering",
        summary: "Essays on Software Engineering",
        tableOfContents: "Classic Reads",
        currentstate: false,
        bookSize: 3, 
      },
      {
        id: "9",
        title: "Working Effectively with Legacy Code",
        author: "Michael Feathers",
        publisher: "Prentice Hall",
        publishYear: "2004-09-01",
        genre: "Software Engineering",
        summary: "Refactoring and maintaining old codebases",
        tableOfContents: "Essential for Developers",
        currentstate: true,
        location: 4, 
        bookSize: 2, 
      },
      {
        id: "10",
        title: "Code Complete",
        author: "Steve McConnell",
        publisher: "Microsoft Press",
        publishYear: "2004-06-19",
        genre: "Programming",
        summary: "A practical handbook of software construction",
        tableOfContents: "Best Practices",
        currentstate: false,
        bookSize: 1, 
      },
      {
        id: "11",
        title: "The Art of Computer Programming",
        author: "Donald Knuth",
        publisher: "Addison-Wesley",
        publishYear: "1968-01-01",
        genre: "Computer Science",
        summary: "A fundamental work on algorithms and programming techniques",
        tableOfContents: "Advanced Books",
        currentstate: true,
        location: 2, 
        bookSize: 3, 
      },
      {
        id: "12",
        title: "Introduction to the Theory of Computation",
        author: "Michael Sipser",
        publisher: "Cengage Learning",
        publishYear: "1996-01-01",
        genre: "Computer Science",
        summary: "A comprehensive introduction to computation theory",
        tableOfContents: "Theoretical CS",
        currentstate: false,
        bookSize: 2, 
      },
      {
        id: "13",
        title: "Deep Learning",
        author: "Ian Goodfellow, Yoshua Bengio, Aaron Courville",
        publisher: "MIT Press",
        publishYear: "2016-11-18",
        genre: "Artificial Intelligence",
        summary: "An in-depth introduction to deep learning techniques",
        tableOfContents: "AI & ML",
        currentstate: true,
        location: 3, 
        bookSize: 2, 
      },
      {
        id: "14",
        title: "Artificial Intelligence: A Modern Approach",
        author: "Stuart Russell, Peter Norvig",
        publisher: "Pearson",
        publishYear: "2020-04-28",
        genre: "Artificial Intelligence",
        summary: "A comprehensive textbook on AI",
        tableOfContents: "AI & ML",
        currentstate: false,
        bookSize: 3, 
      },
      {
        id: "15",
        title: "Computer Networking: A Top-Down Approach",
        author: "James F. Kurose, Keith W. Ross",
        publisher: "Pearson",
        publishYear: "2020-03-20",
        genre: "Networking",
        summary: "Understanding networking from a top-down perspective",
        tableOfContents: "Networking Books",
        currentstate: true,
        location: 3, 
        bookSize: 1, 
      },
    ],
  };